---
title: "02estimate"
author: "Suguru Otani"
date: "2022/12/03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load

```{r,echo=FALSE,results = 'asis'}
rm(list = ls())
library(magrittr)
library(ggplot2)
# set constant ----
n_observation_list <-
  c(
    50,
    100, 
    200, 
    1000
    )
sigma_list <-
  c(
    0,
    0.001,
    0.5,
    1.0, 
    2.0
    )
for(nn in 1:length(n_observation_list)){
  for(ss in 1:length(sigma_list)){
    temp_nn <-
      n_observation_list[nn]
    temp_sigma <-
      sigma_list[ss]
    filename <-
      paste(
        "linear_linear_",
        "n_",
        temp_nn,
        "_sigma_",
        temp_sigma,
        sep = ""
      )
    temp_data <-
      readRDS(
        file =
          here::here(
            paste(
              "output/",
              "parameter_hat_table",
              filename,
              ".rds",
              sep = ""
              )
            )
        )
    assign(
      filename,
      temp_data)
  }
}
# "alpha2_0",

sigma_list <-
  c(
    0.001,
    0.5,
    1.0, 
    2.0
    )
for(nn in 1:length(n_observation_list)){
  for(ss in 1:length(sigma_list)){
    temp_nn <-
      n_observation_list[nn]
    temp_sigma <-
      sigma_list[ss]
    filename <-
      paste(
        "linear_linear_",
        "n_",
        temp_nn,
        "_sigma_",
        temp_sigma,
        "alpha2_0",
        sep = ""
      )
    temp_data <-
      readRDS(
        file =
          here::here(
            paste(
              "output/",
              "parameter_hat_table",
              filename,
              ".rds",
              sep = ""
              )
            )
        )
    assign(
      filename,
      temp_data)
  }
}

sigma_list <-
  c(
    0.001,
    0.5,
    1.0, 
    2.0
    )

for(nn in 1:length(n_observation_list)){
  for(ss in 1:length(sigma_list)){
    temp_nn <-
      n_observation_list[nn]
    temp_sigma <-
      sigma_list[ss]
    filename <-
      paste(
        "linear_linear_",
        "n_",
        temp_nn,
        "_sigma_",
        temp_sigma,
        "_without_demand_shifter_y",
        sep = ""
      )
    temp_data <-
      readRDS(
        file =
          here::here(
            paste(
              "output/",
              "parameter_hat_table",
              filename,
              ".rds",
              sep = ""
              )
            )
        )
    assign(
      filename,
      temp_data)
  }
}
options(modelsummary_format_numeric_latex = "plain") # for modelsummary output
```


# Estimation {.tabset}

## linear-demand linear-cost {.tabset}

### $\sigma = 0.001$ {.tabset}

#### $n = 50$

```{r,echo=FALSE,results = 'asis'}
cat("with demand shifter y")
modelsummary::datasummary_skim(
  fmt = 3,
  linear_linear_n_50_sigma_0.001)
cat("without demand shifter y")
modelsummary::datasummary_skim(
  fmt = 3,
  linear_linear_n_50_sigma_0.001_without_demand_shifter_y)
```

#### $n = 100$

```{r,echo=FALSE,results = 'asis'}
cat("with demand shifter y")
modelsummary::datasummary_skim(
  fmt = 3,
  linear_linear_n_100_sigma_0.001)
cat("without demand shifter y")
modelsummary::datasummary_skim(
  fmt = 3,
  linear_linear_n_100_sigma_0.001_without_demand_shifter_y)
```

#### $n = 200$

```{r,echo=FALSE,results = 'asis'}
cat("with demand shifter y")
modelsummary::datasummary_skim(
  fmt = 3,
  linear_linear_n_200_sigma_0.001)
cat("without demand shifter y")
modelsummary::datasummary_skim(
  fmt = 3,
  linear_linear_n_200_sigma_0.001_without_demand_shifter_y)
```

#### $n = 1000$

```{r,echo=FALSE,results = 'asis'}
cat("with demand shifter y")
modelsummary::datasummary_skim(
  fmt = 3,
  linear_linear_n_1000_sigma_0.001)
cat("without demand shifter y")
modelsummary::datasummary_skim(
  fmt = 3,
  linear_linear_n_1000_sigma_0.001_without_demand_shifter_y)
```


### $\sigma = 0.5$ {.tabset}

#### $n = 50$

```{r,echo=FALSE,results = 'asis'}
cat("with demand shifter y")
modelsummary::datasummary_skim(
  fmt = 3,
  linear_linear_n_50_sigma_0.5)
cat("without demand shifter y")
modelsummary::datasummary_skim(
  fmt = 3,
  linear_linear_n_50_sigma_0.5_without_demand_shifter_y)
```

#### $n = 100$

```{r,echo=FALSE,results = 'asis'}
cat("with demand shifter y")
modelsummary::datasummary_skim(
  fmt = 3,
  linear_linear_n_100_sigma_0.5)
cat("without demand shifter y")
modelsummary::datasummary_skim(
  fmt = 3,
  linear_linear_n_100_sigma_0.5_without_demand_shifter_y)
```

#### $n = 200$

```{r,echo=FALSE,results = 'asis'}
cat("with demand shifter y")
modelsummary::datasummary_skim(
  fmt = 3,
  linear_linear_n_200_sigma_0.5)
cat("without demand shifter y")
modelsummary::datasummary_skim(
  fmt = 3,
  linear_linear_n_200_sigma_0.5_without_demand_shifter_y)
```

#### $n = 1000$

```{r,echo=FALSE,results = 'asis'}
cat("with demand shifter y")
modelsummary::datasummary_skim(
  fmt = 3,
  linear_linear_n_1000_sigma_0.5)
cat("without demand shifter y")
modelsummary::datasummary_skim(
  fmt = 3,
  linear_linear_n_1000_sigma_0.5_without_demand_shifter_y)
```




### $\sigma = 1$ {.tabset}

#### $n = 50$

```{r,echo=FALSE,results = 'asis'}
cat("with demand shifter y")
modelsummary::datasummary_skim(
  fmt = 3,
  linear_linear_n_50_sigma_1)
cat("without demand shifter y")
modelsummary::datasummary_skim(
  fmt = 3,
  linear_linear_n_50_sigma_1_without_demand_shifter_y)
```

#### $n = 100$

```{r,echo=FALSE,results = 'asis'}
cat("with demand shifter y")
modelsummary::datasummary_skim(
  fmt = 3,
  linear_linear_n_100_sigma_1)
cat("without demand shifter y")
modelsummary::datasummary_skim(
  fmt = 3,
  linear_linear_n_100_sigma_1_without_demand_shifter_y)
```

#### $n = 200$

```{r,echo=FALSE,results = 'asis'}
cat("with demand shifter y")
modelsummary::datasummary_skim(
  fmt = 3,
  linear_linear_n_200_sigma_1)
cat("without demand shifter y")
modelsummary::datasummary_skim(
  fmt = 3,
  linear_linear_n_200_sigma_1_without_demand_shifter_y)
```

#### $n = 1000$

```{r,echo=FALSE,results = 'asis'}
cat("with demand shifter y")
modelsummary::datasummary_skim(
  fmt = 3,
  linear_linear_n_1000_sigma_1)
cat("without demand shifter y")
modelsummary::datasummary_skim(
  fmt = 3,
  linear_linear_n_1000_sigma_1_without_demand_shifter_y)
```


### $\sigma = 2$ {.tabset}

#### $n = 50$

```{r,echo=FALSE,results = 'asis'}
cat("with demand shifter y")
modelsummary::datasummary_skim(
  fmt = 3,
  linear_linear_n_50_sigma_2)
cat("without demand shifter y")
modelsummary::datasummary_skim(
  fmt = 3,
  linear_linear_n_50_sigma_2_without_demand_shifter_y)
```

#### $n = 100$

```{r,echo=FALSE,results = 'asis'}
cat("with demand shifter y")
modelsummary::datasummary_skim(
  fmt = 3,
  linear_linear_n_100_sigma_2)
cat("without demand shifter y")
modelsummary::datasummary_skim(
  fmt = 3,
  linear_linear_n_100_sigma_2_without_demand_shifter_y)
```

#### $n = 200$

```{r,echo=FALSE,results = 'asis'}
cat("with demand shifter y")
modelsummary::datasummary_skim(
  fmt = 3,
  linear_linear_n_200_sigma_2)
cat("without demand shifter y")
modelsummary::datasummary_skim(
  fmt = 3,
  linear_linear_n_200_sigma_2_without_demand_shifter_y)
```

#### $n = 1000$

```{r,echo=FALSE,results = 'asis'}
cat("with demand shifter y")
modelsummary::datasummary_skim(
  fmt = 3,
  linear_linear_n_1000_sigma_2)
cat("without demand shifter y")
modelsummary::datasummary_skim(
  fmt = 3,
  linear_linear_n_1000_sigma_2_without_demand_shifter_y)
```


### Appendix: linear with zero sigma {.tabset}

#### $n = 50$

```{r,echo=FALSE,results = 'asis'}
cat("with demand shifter y")
modelsummary::datasummary_skim(
  fmt = 3,
  linear_linear_n_50_sigma_0)
```

#### $n = 100$

```{r,echo=FALSE,results = 'asis'}
cat("with demand shifter y")
modelsummary::datasummary_skim(
  fmt = 3,
  linear_linear_n_100_sigma_0)

```

#### $n = 200$

```{r,echo=FALSE,results = 'asis'}
cat("with demand shifter y")
modelsummary::datasummary_skim(
  fmt = 3,
  linear_linear_n_200_sigma_0)

```

#### $n = 1000$

```{r,echo=FALSE,results = 'asis'}
cat("with demand shifter y")
modelsummary::datasummary_skim(
  fmt = 3,
  linear_linear_n_1000_sigma_0)
```

### Appendix: linear with zero alpha2 {.tabset}

#### $\sigma = 0.001$ {.tabset}

##### $n = 50$

```{r,echo=FALSE,results = 'asis'}
cat("with demand shifter y")
modelsummary::datasummary_skim(
  fmt = 3,
  linear_linear_n_50_sigma_0.001alpha2_0)
```

##### $n = 100$

```{r,echo=FALSE,results = 'asis'}
cat("with demand shifter y")
modelsummary::datasummary_skim(
  fmt = 3,
  linear_linear_n_100_sigma_0.001alpha2_0)

```

##### $n = 200$

```{r,echo=FALSE,results = 'asis'}
cat("with demand shifter y")
modelsummary::datasummary_skim(
  fmt = 3,
  linear_linear_n_200_sigma_0.001alpha2_0)

```

##### $n = 1000$

```{r,echo=FALSE,results = 'asis'}
cat("with demand shifter y")
modelsummary::datasummary_skim(
  fmt = 3,
  linear_linear_n_1000_sigma_0.001alpha2_0)
```


#### $\sigma = 0.5$ {.tabset}

##### $n = 50$

```{r,echo=FALSE,results = 'asis'}
cat("with demand shifter y")
modelsummary::datasummary_skim(
  fmt = 3,
  linear_linear_n_50_sigma_0.5alpha2_0)
```

##### $n = 100$

```{r,echo=FALSE,results = 'asis'}
cat("with demand shifter y")
modelsummary::datasummary_skim(
  fmt = 3,
  linear_linear_n_100_sigma_0.5alpha2_0)

```

##### $n = 200$

```{r,echo=FALSE,results = 'asis'}
cat("with demand shifter y")
modelsummary::datasummary_skim(
  fmt = 3,
  linear_linear_n_200_sigma_0.5alpha2_0)

```

##### $n = 1000$

```{r,echo=FALSE,results = 'asis'}
cat("with demand shifter y")
modelsummary::datasummary_skim(
  fmt = 3,
  linear_linear_n_1000_sigma_0.5alpha2_0)
```


#### $\sigma = 1$ {.tabset}

##### $n = 50$

```{r,echo=FALSE,results = 'asis'}
cat("with demand shifter y")
modelsummary::datasummary_skim(
  fmt = 3,
  linear_linear_n_50_sigma_1alpha2_0)
```

##### $n = 100$

```{r,echo=FALSE,results = 'asis'}
cat("with demand shifter y")
modelsummary::datasummary_skim(
  fmt = 3,
  linear_linear_n_100_sigma_1alpha2_0)

```

##### $n = 200$

```{r,echo=FALSE,results = 'asis'}
cat("with demand shifter y")
modelsummary::datasummary_skim(
  fmt = 3,
  linear_linear_n_200_sigma_1alpha2_0)

```

##### $n = 1000$

```{r,echo=FALSE,results = 'asis'}
cat("with demand shifter y")
modelsummary::datasummary_skim(
  fmt = 3,
  linear_linear_n_1000_sigma_1alpha2_0)
```


#### $\sigma = 2$ {.tabset}

##### $n = 50$

```{r,echo=FALSE,results = 'asis'}
cat("with demand shifter y")
modelsummary::datasummary_skim(
  fmt = 3,
  linear_linear_n_50_sigma_2alpha2_0)
```

##### $n = 100$

```{r,echo=FALSE,results = 'asis'}
cat("with demand shifter y")
modelsummary::datasummary_skim(
  fmt = 3,
  linear_linear_n_100_sigma_2alpha2_0)

```

##### $n = 200$

```{r,echo=FALSE,results = 'asis'}
cat("with demand shifter y")
modelsummary::datasummary_skim(
  fmt = 3,
  linear_linear_n_200_sigma_2alpha2_0)

```

##### $n = 1000$

```{r,echo=FALSE,results = 'asis'}
cat("with demand shifter y")
modelsummary::datasummary_skim(
  fmt = 3,
  linear_linear_n_1000_sigma_2alpha2_0)
```

