---
title: "04_2construct_figuretable"
author: "Suguru Otani"
date: "2022/12/03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load

```{r,echo=FALSE,results = "hide"}
rm(list = ls())
library(magrittr)
library(ggplot2)
# we need to use old version of modelsummary for latex output
if(1 == 0){
  devtools::install_version(
    "modelsummary",
    version = "0.9.4", 
    repos = "http://cran.us.r-project.org")
  }
library(modelsummary) # for N in datasummary
# set constant ----
n_observation_list <-
  c(
    50,
    100, 
    200, 
    1000
    )
sigma_list <-
  c(
    0.001,
    0.5, 
    1.0, 
    2.0
    )

# linear with demand shifter
for(nn in 1:length(n_observation_list)){
  for(ss in 1:length(sigma_list)){
    temp_nn <-
      n_observation_list[nn]
    temp_sigma <-
      sigma_list[ss]
    filename <-
      paste(
        "linear_linear_",
        "n_",
        temp_nn,
        "_sigma_",
        temp_sigma,
        sep = ""
      )
    temp_data <-
      readRDS(
        file =
          here::here(
            paste(
              "output/",
              "parameter_hat_table",
              filename,
              ".rds",
              sep = ""
              )
            )
        )
    temp_data <-
      temp_data %>% 
      dplyr::rename(
        `$\\alpha_{0}$` =
          alpha0_hat,
        `$\\alpha_{1}$` =
          alpha1_hat,
        `$\\alpha_{2}$` =
          alpha2_hat,
        `$\\alpha_{3}$` =
          alpha3_hat,
        `$\\gamma_{0}$` =
          gamma0_hat,
        `$\\gamma_{1}$` =
          gamma1_hat,
        `$\\gamma_{2}$` =
          gamma2_hat,
        `$\\gamma_{3}$` =
          gamma3_hat,
        `$\\theta$` =
          theta_hat,
        `Mean $R^{2}$ (demand)` =
          R2_demand,
        `Mean $R^{2}$ (supply)` =
          R2_supply) %>% 
      dplyr::mutate(
        filename =
          paste(
            "(",
            nn,
            ") ",
            "$n=",
            temp_nn,
            "$",
            sep = ""
            )
        )
    assign(
      filename,
      temp_data) 
  }
}


# mpec linear with demand shifter
for(nn in 1:length(n_observation_list)){
  for(ss in 1:length(sigma_list)){
    temp_nn <-
      n_observation_list[nn]
    temp_sigma <-
      sigma_list[ss]
    filename <-
      paste(
        "linear_linear_",
        "n_",
        temp_nn,
        "_sigma_",
        temp_sigma,
        "_mpec_linear_non_constraint_non_constraint",
        sep = ""
      )
    temp_data <-
      readr::read_csv(
          file =
            here::here(
              paste(
                "output/",
                "parameter_hat_table_mpec_",
                filename,
                ".csv",
                sep = ""
                )
              ),
          show_col_types = FALSE
          )
    # drop T, sigma, status
      temp_data <-
        temp_data[
          ,-c(
            1, # T
            2, # sigma
            12 # status
            )]
      colnames(temp_data) <-
        c(
          "alpha0_hat",
          "alpha1_hat",
          "alpha2_hat",
          "alpha3_hat",
          "gamma0_hat",
          "gamma1_hat",
          "gamma2_hat",
          "gamma3_hat",
          "theta_hat",
          "status_indicator"
          )
    temp_data <-
      temp_data %>% 
      dplyr::rename(
        `$\\alpha_{0}$` =
          alpha0_hat,
        `$\\alpha_{1}$` =
          alpha1_hat,
        `$\\alpha_{2}$` =
          alpha2_hat,
        `$\\alpha_{3}$` =
          alpha3_hat,
        `$\\gamma_{0}$` =
          gamma0_hat,
        `$\\gamma_{1}$` =
          gamma1_hat,
        `$\\gamma_{2}$` =
          gamma2_hat,
        `$\\gamma_{3}$` =
          gamma3_hat,
        `$\\theta$` =
          theta_hat) %>% 
      dplyr::mutate(
        filename =
          paste(
            "(",
            nn,
            ") ",
            "$n=",
            temp_nn,
            "$",
            sep = ""
            )
        )
    assign(
      filename,
      temp_data)
  }
}


# linear without demand shifter
for(nn in 1:length(n_observation_list)){
  for(ss in 1:length(sigma_list)){
    temp_nn <-
      n_observation_list[nn]
    temp_sigma <-
      sigma_list[ss]
    filename <-
      paste(
        "linear_linear_",
        "n_",
        temp_nn,
        "_sigma_",
        temp_sigma,
        "_without_demand_shifter_y",
        sep = ""
      )
    temp_data <-
      readRDS(
        file =
          here::here(
            paste(
              "output/",
              "parameter_hat_table",
              filename,
              ".rds",
              sep = ""
              )
            )
        )
    temp_data <-
      temp_data %>% 
      dplyr::rename(
        `$\\alpha_{0}$` =
          alpha0_hat,
        `$\\alpha_{1}$` =
          alpha1_hat,
        `$\\alpha_{2}$` =
          alpha2_hat,
        # `$\\alpha_{3}$` =
        #   alpha3_hat,
        `$\\gamma_{0}$` =
          gamma0_hat,
        `$\\gamma_{1}$` =
          gamma1_hat,
        `$\\gamma_{2}$` =
          gamma2_hat,
        # `$\\gamma_{3}$` =
        #   gamma3_hat,
        `$\\theta$` =
          theta_hat,
        `Mean $R^{2}$ (demand)` =
          R2_demand,
        `Mean $R^{2}$ (supply)` =
          R2_supply) %>% 
      dplyr::mutate(
        filename =
          paste(
            "(",
            nn,
            ") ",
            "$n=",
            temp_nn,
            "$",
            sep = ""
            )
        )
    assign(
      filename,
      temp_data)
  }
}
constraint_list <-
  c(
    "_separate_non_constraint_non_constraint",
    "_separate_non_constraint_theta_constraint"
    )
# loglinear with constraint
for(nn in 1:length(n_observation_list)){
  for(ss in 1:length(sigma_list)){
    for(cc in 1:length(constraint_list)){
      temp_nn <-
        n_observation_list[nn]
      temp_sigma <-
        sigma_list[ss]
      temp_constraint <-
        constraint_list[cc]
      filename <-
        paste(
          "loglinear_loglinear_",
          "n_",
          temp_nn,
          "_sigma_",
          temp_sigma,
          temp_constraint,
          sep = ""
          )
      temp_data <-
        readr::read_csv(
          file =
            here::here(
              paste(
                "output/",
                "parameter_hat_table_",
                filename,
                ".csv",
                sep = ""
                )
              ),
          show_col_types = FALSE
          )
      # drop T, sigma, status
      temp_data <-
        temp_data[
          ,-c(
            1, # T
            2, # sigma
            12 # status
            )]
      colnames(temp_data) <-
        c(
          "alpha0_hat",
          "alpha1_hat",
          "alpha2_hat",
          "alpha3_hat",
          "gamma0_hat",
          "gamma1_hat",
          "gamma2_hat",
          "gamma3_hat",
          "theta_hat",
          "status_indicator"
          )
      temp_data <-
        temp_data %>% 
        dplyr::rename(
          `$\\alpha_{0}$` =
            alpha0_hat,
          `$\\alpha_{1}$` =
            alpha1_hat,
          `$\\alpha_{2}$` =
            alpha2_hat,
          `$\\alpha_{3}$` =
            alpha3_hat,
          `$\\gamma_{0}$` =
            gamma0_hat,
          `$\\gamma_{1}$` =
            gamma1_hat,
          `$\\gamma_{2}$` =
            gamma2_hat,
          `$\\gamma_{3}$` =
            gamma3_hat,
          `$\\theta$` =
            theta_hat#,
        # `Mean $R^{2}$ (demand)` =
        #   R2_demand,
        # `Mean $R^{2}$ (supply)` =
        #   R2_supply
        ) %>% 
      dplyr::mutate(
        filename =
          paste(
            "(",
            nn,
            ") ",
            "$n=",
            temp_nn,
            "$",
            sep = ""
            ),
        locally_solved_percent =
          format(
            round(
              sum(
                status_indicator,
                na.rm = TRUE)/
                dim(temp_data)[1],
              digits = 3) * 100,
               nsmall = 3)
        )
    assign(
      filename,
      temp_data) 
    
    }
  }
}

true_parameter_linear <-
  c(
    10,
    rep(1, 7),
    0.5
    )
true_parameter_loglinear <-
  c(
    1,
    1,
    0.1,#target_alpha2
    1,
    rep(1, 4),
    0.3
    )

create_table_with_demand_shifter_bias_rmse <-
  function(target_data){
    bias_info <-
      target_data %>% 
      dplyr::group_by(filename) %>% 
      # Redefine variables as the errors
      dplyr::summarise(
        `$\\alpha_{0}$` =
          mean(`$\\alpha_{0}$` -
                 true_parameter_linear[1],
               na.rm = TRUE),
        `$\\alpha_{1}$` =
          mean(`$\\alpha_{1}$` -
                 true_parameter_linear[2],
               na.rm = TRUE),
        `$\\alpha_{2}$` =
          mean(`$\\alpha_{2}$` -
                 true_parameter_linear[3],
               na.rm = TRUE),
        `$\\alpha_{3}$` =
          mean(`$\\alpha_{3}$` -
                 true_parameter_linear[4],
               na.rm = TRUE),
        `$\\gamma_{0}$` =
          mean(`$\\gamma_{0}$` -
                 true_parameter_linear[5],
               na.rm = TRUE),
        `$\\gamma_{1}$` =
          mean(`$\\gamma_{1}$` - 
                 true_parameter_linear[6],
               na.rm = TRUE),
        `$\\gamma_{2}$` =
          mean(`$\\gamma_{2}$` - 
                 true_parameter_linear[7],
               na.rm = TRUE),
        `$\\gamma_{3}$` =
          mean(`$\\gamma_{3}$` -
                 true_parameter_linear[8],
               na.rm = TRUE),
        `$\\theta$` =
          mean(`$\\theta$` -
                 true_parameter_linear[9],
               na.rm = TRUE)
      ) %>% 
      dplyr::ungroup()
    rmse_info <-
      target_data %>% 
      dplyr::group_by(filename) %>% 
      dplyr::summarise(
        `$\\alpha_{0}$` =
          sqrt(mean((`$\\alpha_{0}$` -
                       true_parameter_linear[1])^2,
               na.rm = TRUE)),
        `$\\alpha_{1}$` =
          sqrt(mean((`$\\alpha_{1}$` -
                       true_parameter_linear[2])^2,
               na.rm = TRUE)),
        `$\\alpha_{2}$` =
          sqrt(mean((`$\\alpha_{2}$` -
                       true_parameter_linear[3])^2,
               na.rm = TRUE)),
        `$\\alpha_{3}$` =
          sqrt(mean((`$\\alpha_{3}$` -
                       true_parameter_linear[4])^2,
               na.rm = TRUE)),
        `$\\gamma_{0}$` =
          sqrt(mean((`$\\gamma_{0}$` -
                       true_parameter_linear[5])^2,
               na.rm = TRUE)),
        `$\\gamma_{1}$` =
          sqrt(mean((`$\\gamma_{1}$` -
                       true_parameter_linear[6])^2,
               na.rm = TRUE)),
        `$\\gamma_{2}$` =
          sqrt(mean((`$\\gamma_{2}$` -
                       true_parameter_linear[7])^2,
               na.rm = TRUE)),
        `$\\gamma_{3}$` =
          sqrt(mean((`$\\gamma_{3}$` -
                       true_parameter_linear[8])^2,
               na.rm = TRUE)),
        `$\\theta$` =
          sqrt(mean((`$\\theta$` -
                       true_parameter_linear[9])^2,
               na.rm = TRUE))
      ) %>% 
      dplyr::ungroup()
    file_name_list <-
      unique(
        rmse_info$filename)
    for(nn in 1:length(file_name_list)){
      temp_file_name <-
        as.character(
          file_name_list[nn])
      temp_bias <-
        bias_info %>% 
        dplyr::filter(
          filename == 
            temp_file_name
        )
      temp_rmse <-
        rmse_info %>% 
        dplyr::filter(
          filename == 
            temp_file_name
          )
      temp_bias_rmse <-
        data.frame(
          "Bias" = 
            format(
              round(
                t(temp_bias[-1]),
                digits = 3),
              nsmall = 3),
          "RMSE" = 
            format(
              round(
                t(temp_rmse[-1]),
                digits = 3),
              nsmall = 3)
          )
      if(nn == 1){
        all_bias_rmse <-
          temp_bias_rmse
      }else{
        #merge 
        all_bias_rmse <-
          cbind(
            all_bias_rmse,
            temp_bias_rmse)
      }
    }
    new_rows <-
      data.frame(
        #"Sample size ($T$)",
        "",
        "50",
        "",
        "100",
        "",
        "200",
        "",
        "1000")
    colnames(new_rows) <-
      colnames(all_bias_rmse)
    all_bias_rmse_for_latex <-
      rbind(
        all_bias_rmse,
        new_rows
        )
    rownames(all_bias_rmse_for_latex)[10] <-
      "Sample size ($T$)"
    filelocation <-
      paste(
        "figuretable/",
        deparse(
          substitute(
            target_data
            )
          ),
        as.character(),
        "_bias_rmse",
        ".tex",
        sep = "")
    all_bias_rmse_for_latex %>% 
      kableExtra::kbl(
        format = "latex",
        align = c("l","r","r","r","r","r","r","r","r"),
        escape = FALSE,
        booktabs = TRUE,
        linesep = ""
      ) %>% 
      kableExtra::save_kable(
        file = here::here(
          filelocation
        )
      )
    res <-
      all_bias_rmse_for_latex %>% 
      kableExtra::kable() %>% 
      kableExtra::kable_styling()
    return(res)
  }

create_table_loglinear_with_demand_shifter_bias_rmse <-
  function(target_data){
    # pick up locally solved id
    # target_data <-
    #   target_data %>%
    #    dplyr::filter(
    #      status_indicator == 1
    #    )
    bias_info <-
      target_data %>%
       dplyr::filter(
         status_indicator == 1
       ) %>% 
      dplyr::group_by(filename) %>% 
      # Redefine variables as the errors
      dplyr::summarise(
        `$\\alpha_{0}$` =
          mean(`$\\alpha_{0}$` -
                 true_parameter_loglinear[1],
               na.rm = TRUE),
        `$\\alpha_{1}$` =
          mean(`$\\alpha_{1}$` -
                 true_parameter_loglinear[2],
               na.rm = TRUE),
        `$\\alpha_{2}$` =
          mean(`$\\alpha_{2}$` -
                 true_parameter_loglinear[3],
               na.rm = TRUE),
        `$\\alpha_{3}$` =
          mean(`$\\alpha_{3}$` -
                 true_parameter_loglinear[4],
               na.rm = TRUE),
        `$\\gamma_{0}$` =
          mean(`$\\gamma_{0}$` - 
                 true_parameter_loglinear[5],
               na.rm = TRUE),
        `$\\gamma_{1}$` =
          mean(`$\\gamma_{1}$` -
                 true_parameter_loglinear[6],
               na.rm = TRUE),
        `$\\gamma_{2}$` =
          mean(`$\\gamma_{2}$` -
                 true_parameter_loglinear[7],
               na.rm = TRUE),
        `$\\gamma_{3}$` =
          mean(`$\\gamma_{3}$` - 
                 true_parameter_loglinear[8],
               na.rm = TRUE),
        `$\\theta$` =
          mean(`$\\theta$` -
                 true_parameter_loglinear[9],
               na.rm = TRUE)
      ) %>% 
      dplyr::ungroup()
    rmse_info <-
      target_data %>%
       dplyr::filter(
         status_indicator == 1
       ) %>% 
      dplyr::group_by(filename) %>% 
      dplyr::summarise(
        `$\\alpha_{0}$` =
          sqrt(mean((`$\\alpha_{0}$` -
                       true_parameter_loglinear[1])^2,
               na.rm = TRUE)),
        `$\\alpha_{1}$` =
          sqrt(mean((`$\\alpha_{1}$` -
                       true_parameter_loglinear[2])^2,
               na.rm = TRUE)),
        `$\\alpha_{2}$` =
          sqrt(mean((`$\\alpha_{2}$` -
                       true_parameter_loglinear[3])^2,
               na.rm = TRUE)),
        `$\\alpha_{3}$` =
          sqrt(mean((`$\\alpha_{3}$` -
                       true_parameter_loglinear[4])^2,
               na.rm = TRUE)),
        `$\\gamma_{0}$` =
          sqrt(mean((`$\\gamma_{0}$` -
                       true_parameter_loglinear[5])^2,
               na.rm = TRUE)),
        `$\\gamma_{1}$` =
          sqrt(mean((`$\\gamma_{1}$` -
                       true_parameter_loglinear[6])^2,
               na.rm = TRUE)),
        `$\\gamma_{2}$` =
          sqrt(mean((`$\\gamma_{2}$` -
                       true_parameter_loglinear[7])^2,
               na.rm = TRUE)),
        `$\\gamma_{3}$` =
          sqrt(mean((`$\\gamma_{3}$` -
                       true_parameter_loglinear[8])^2,
               na.rm = TRUE)),
        `$\\theta$` =
          sqrt(mean((`$\\theta$` -
                       true_parameter_loglinear[9])^2,
               na.rm = TRUE))
      ) %>% 
      dplyr::ungroup()
    file_name_list <-
      unique(rmse_info$filename)
    for(nn in 1:length(file_name_list)){
      temp_file_name <-
        as.character(
          file_name_list[nn])
      temp_bias <-
        bias_info %>% 
        dplyr::filter(
          filename == 
            temp_file_name
        )
      temp_rmse <-
        rmse_info %>% 
        dplyr::filter(
          filename == 
            temp_file_name
          )
      temp_bias_rmse <-
        data.frame(
          "Bias" = 
            format(
              round(
                t(temp_bias[-1]),
                digits = 3),
              nsmall = 3),
          "RMSE" = 
            format(
              round(
                t(temp_rmse[-1]),
                digits = 3),
              nsmall = 3)
          )
      if(nn == 1){
        all_bias_rmse <-
          temp_bias_rmse
      }else{
        #merge 
        all_bias_rmse <-
          cbind(
            all_bias_rmse,
            temp_bias_rmse)
      }
    }
    new_rows <-
      data.frame(
        #"Sample size ($T$)",
        "",
        "50",
        "",
        "100",
        "",
        "200",
        "",
        "1000")
    locally_solved_list <-
      target_data %>% 
      dplyr::distinct(
        filename,
        locally_solved_percent
      )
    locally_solved_row <- 
      data.frame(
        #"Runs converged (\\%)",
        "",
        locally_solved_list[1,2],
        "",
        locally_solved_list[2,2],
        "",
        locally_solved_list[3,2],
        "",
        locally_solved_list[4,2])
    # keep consistency of colnames for latex
    colnames(new_rows) <-
      colnames(all_bias_rmse)
    colnames(locally_solved_row) <-
      colnames(all_bias_rmse)
    all_bias_rmse_for_latex <-
      rbind(
        all_bias_rmse,
        locally_solved_row,
        new_rows)
    rownames(all_bias_rmse_for_latex)[10] <-
      "Runs converged (\\%)"
    rownames(all_bias_rmse_for_latex)[11] <-
      "Sample size ($T$)"
    filelocation <-
      paste(
        "figuretable/",
        deparse(
          substitute(
            target_data
            )
          ),
        as.character(),
        "_bias_rmse",
        ".tex",
        sep = "")
    all_bias_rmse_for_latex %>%
      kableExtra::kbl(
        format = "latex",
        align = c("l","r","r","r","r","r","r","r","r"),
        escape = FALSE,
        booktabs = TRUE,
        linesep = ""
      ) %>%
      kableExtra::save_kable(
        file = here::here(
          filelocation
        )
      )
    res <-
      all_bias_rmse_for_latex %>% 
      kableExtra::kable() %>% 
      kableExtra::kable_styling()
    return(res)
  }

options(modelsummary_format_numeric_latex = "plain") # for modelsummary output
```


# Estimation {.tabset}

## linear-demand linear-cost {.tabset}

### with demand shifter {.tabset}

#### 2SLS

```{r,echo=FALSE,results = "asis"}
linear_linear_sigma_0.001 <-
  rbind(
    linear_linear_n_50_sigma_0.001,
    linear_linear_n_100_sigma_0.001,
    linear_linear_n_200_sigma_0.001,
    linear_linear_n_1000_sigma_0.001)

create_table_with_demand_shifter_bias_rmse(
  linear_linear_sigma_0.001
)
linear_linear_sigma_0.5 <-
  rbind(
    linear_linear_n_50_sigma_0.5,
    linear_linear_n_100_sigma_0.5,
    linear_linear_n_200_sigma_0.5,
    linear_linear_n_1000_sigma_0.5)
create_table_with_demand_shifter_bias_rmse(
  linear_linear_sigma_0.5
)

linear_linear_sigma_1 <-
  rbind(
    linear_linear_n_50_sigma_1,
    linear_linear_n_100_sigma_1,
    linear_linear_n_200_sigma_1,
    linear_linear_n_1000_sigma_1)
create_table_with_demand_shifter_bias_rmse(
  linear_linear_sigma_1
)

linear_linear_sigma_2 <-
  rbind(
    linear_linear_n_50_sigma_2,
    linear_linear_n_100_sigma_2,
    linear_linear_n_200_sigma_2,
    linear_linear_n_1000_sigma_2)
create_table_with_demand_shifter_bias_rmse(
  linear_linear_sigma_2
)

```

#### MPEC

```{r,echo=FALSE,results = "asis"}
linear_linear_sigma_0.001_mpec_linear_non_constraint_non_constraint <-
  rbind(
    linear_linear_n_50_sigma_0.001_mpec_linear_non_constraint_non_constraint,
    linear_linear_n_100_sigma_0.001_mpec_linear_non_constraint_non_constraint,
    linear_linear_n_200_sigma_0.001_mpec_linear_non_constraint_non_constraint,
    linear_linear_n_1000_sigma_0.001_mpec_linear_non_constraint_non_constraint)

create_table_with_demand_shifter_bias_rmse(
  linear_linear_sigma_0.001_mpec_linear_non_constraint_non_constraint
)
linear_linear_sigma_0.5_mpec_linear_non_constraint_non_constraint <-
  rbind(
    linear_linear_n_50_sigma_0.5_mpec_linear_non_constraint_non_constraint,
    linear_linear_n_100_sigma_0.5_mpec_linear_non_constraint_non_constraint,
    linear_linear_n_200_sigma_0.5_mpec_linear_non_constraint_non_constraint,
    linear_linear_n_1000_sigma_0.5_mpec_linear_non_constraint_non_constraint)
create_table_with_demand_shifter_bias_rmse(
  linear_linear_sigma_0.5_mpec_linear_non_constraint_non_constraint
)

linear_linear_sigma_1_mpec_linear_non_constraint_non_constraint <-
  rbind(
    linear_linear_n_50_sigma_1_mpec_linear_non_constraint_non_constraint,
    linear_linear_n_100_sigma_1_mpec_linear_non_constraint_non_constraint,
    linear_linear_n_200_sigma_1_mpec_linear_non_constraint_non_constraint,
    linear_linear_n_1000_sigma_1_mpec_linear_non_constraint_non_constraint)
create_table_with_demand_shifter_bias_rmse(
  linear_linear_sigma_1_mpec_linear_non_constraint_non_constraint
)

linear_linear_sigma_2_mpec_linear_non_constraint_non_constraint <-
  rbind(
    linear_linear_n_50_sigma_2_mpec_linear_non_constraint_non_constraint,
    linear_linear_n_100_sigma_2_mpec_linear_non_constraint_non_constraint,
    linear_linear_n_200_sigma_2_mpec_linear_non_constraint_non_constraint,
    linear_linear_n_1000_sigma_2_mpec_linear_non_constraint_non_constraint)
create_table_with_demand_shifter_bias_rmse(
  linear_linear_sigma_2_mpec_linear_non_constraint_non_constraint
)

```

## log-linear-demand log-linear-cost with demand shifter {.tabset}

### _separate_non_constraint_non_constraint {.tabset}

```{r,echo=FALSE,results = "asis"}
loglinear_loglinear_sigma_0.001_separate_non_constraint_non_constraint <-
  rbind(
    loglinear_loglinear_n_50_sigma_0.001_separate_non_constraint_non_constraint,
    loglinear_loglinear_n_100_sigma_0.001_separate_non_constraint_non_constraint,
    loglinear_loglinear_n_200_sigma_0.001_separate_non_constraint_non_constraint,
    loglinear_loglinear_n_1000_sigma_0.001_separate_non_constraint_non_constraint
        )
create_table_loglinear_with_demand_shifter_bias_rmse(
  loglinear_loglinear_sigma_0.001_separate_non_constraint_non_constraint
)
loglinear_loglinear_sigma_0.5_separate_non_constraint_non_constraint <-
  rbind(
    loglinear_loglinear_n_50_sigma_0.5_separate_non_constraint_non_constraint,
    loglinear_loglinear_n_100_sigma_0.5_separate_non_constraint_non_constraint,
    loglinear_loglinear_n_200_sigma_0.5_separate_non_constraint_non_constraint,
    loglinear_loglinear_n_1000_sigma_0.5_separate_non_constraint_non_constraint
        )
create_table_loglinear_with_demand_shifter_bias_rmse(
  loglinear_loglinear_sigma_0.5_separate_non_constraint_non_constraint
)

loglinear_loglinear_sigma_1_separate_non_constraint_non_constraint <-
  rbind(
    loglinear_loglinear_n_50_sigma_1_separate_non_constraint_non_constraint,
    loglinear_loglinear_n_100_sigma_1_separate_non_constraint_non_constraint,
    loglinear_loglinear_n_200_sigma_1_separate_non_constraint_non_constraint,
    loglinear_loglinear_n_1000_sigma_1_separate_non_constraint_non_constraint
        )
create_table_loglinear_with_demand_shifter_bias_rmse(
  loglinear_loglinear_sigma_1_separate_non_constraint_non_constraint
)

loglinear_loglinear_sigma_2_separate_non_constraint_non_constraint <-
  rbind(
    loglinear_loglinear_n_50_sigma_2_separate_non_constraint_non_constraint,
    loglinear_loglinear_n_100_sigma_2_separate_non_constraint_non_constraint,
    loglinear_loglinear_n_200_sigma_2_separate_non_constraint_non_constraint,
    loglinear_loglinear_n_1000_sigma_2_separate_non_constraint_non_constraint
        )
create_table_loglinear_with_demand_shifter_bias_rmse(
  loglinear_loglinear_sigma_2_separate_non_constraint_non_constraint
)

```


### _separate_non_constraint_theta_constraint {.tabset}

```{r,echo=FALSE,results = "asis"}
loglinear_loglinear_sigma_0.001_separate_non_constraint_theta_constraint <-
  rbind(
    loglinear_loglinear_n_50_sigma_0.001_separate_non_constraint_theta_constraint,
    loglinear_loglinear_n_100_sigma_0.001_separate_non_constraint_theta_constraint,
    loglinear_loglinear_n_200_sigma_0.001_separate_non_constraint_theta_constraint,
    loglinear_loglinear_n_1000_sigma_0.001_separate_non_constraint_theta_constraint)
create_table_loglinear_with_demand_shifter_bias_rmse(
  loglinear_loglinear_sigma_0.001_separate_non_constraint_theta_constraint
)
loglinear_loglinear_sigma_0.5_separate_non_constraint_theta_constraint <-
  rbind(
    loglinear_loglinear_n_50_sigma_0.5_separate_non_constraint_theta_constraint,
    loglinear_loglinear_n_100_sigma_0.5_separate_non_constraint_theta_constraint,
    loglinear_loglinear_n_200_sigma_0.5_separate_non_constraint_theta_constraint,
    loglinear_loglinear_n_1000_sigma_0.5_separate_non_constraint_theta_constraint)
create_table_loglinear_with_demand_shifter_bias_rmse(
  loglinear_loglinear_sigma_0.5_separate_non_constraint_theta_constraint
)

loglinear_loglinear_sigma_1_separate_non_constraint_theta_constraint <-
  rbind(
    loglinear_loglinear_n_50_sigma_1_separate_non_constraint_theta_constraint,
    loglinear_loglinear_n_100_sigma_1_separate_non_constraint_theta_constraint,
    loglinear_loglinear_n_200_sigma_1_separate_non_constraint_theta_constraint,
    loglinear_loglinear_n_1000_sigma_1_separate_non_constraint_theta_constraint)
create_table_loglinear_with_demand_shifter_bias_rmse(
  loglinear_loglinear_sigma_1_separate_non_constraint_theta_constraint
)

loglinear_loglinear_sigma_2_separate_non_constraint_theta_constraint <-
  rbind(
    loglinear_loglinear_n_50_sigma_2_separate_non_constraint_theta_constraint,
    loglinear_loglinear_n_100_sigma_2_separate_non_constraint_theta_constraint,
    loglinear_loglinear_n_200_sigma_2_separate_non_constraint_theta_constraint,
    loglinear_loglinear_n_1000_sigma_2_separate_non_constraint_theta_constraint)
create_table_loglinear_with_demand_shifter_bias_rmse(
  loglinear_loglinear_sigma_2_separate_non_constraint_theta_constraint
)

```
