---
title: "10_1_simulate_counterexample_for_Lau1982_"
author: "Suguru Otani"
date: "2022/12/03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load

```{r,echo=FALSE,results = "asis"}
rm(list = ls())
library(magrittr)
library(ggplot2)
library(modelsummary) # for N in datasummary
# set constant ----
# set constant ----
n_observation_list <-
  c(
    50,
    100,
    200,
    1000
    )
sigma_list <-
  c(
    0.001,
    0.5,
    1.0,
    2.0
    )

# load, estimate, and save data ----
## linear demand and linear cost ----
### with demand_shifter_y ----
for(nn in 1:length(n_observation_list)){
  for(ss in 1:length(sigma_list)){
    temp_nn <-
      n_observation_list[nn]
    temp_sigma <-
      sigma_list[ss]
    filename <-
      paste(
        "counterexample_for_Lau1982_",
        "n_",
        temp_nn,
        "_sigma_",
        temp_sigma,
        sep = ""
      )
    cat(filename,"\n")
    # load 
    target_data <-
      readRDS(
        file =
          here::here(
            paste(
              "output/data_",
              filename,
              ".rds",
              sep = ""
              )
            )
        )
    assign(
      filename,
      target_data)
  }
}


generate_plot_log_log <-
  function(
    data
  ){
    temp <-
      data %>% 
      dplyr::filter(
        group_id_k < 10)
    x <-
      ggplot(temp,
             aes(x = logQ, y = logP)) + 
      geom_point(alpha = 0.3) + 
      stat_smooth(method = "lm",
                    se = FALSE) +
      theme_classic() + 
      scale_color_viridis_d() +
      theme(legend.position = 'top',
            legend.text = element_text(size=8)) +
      theme(plot.title = element_text(hjust = 0.5)) +
      xlab("logQ") + 
      ylab("logP")
    return(x)
  }

options(modelsummary_format_numeric_latex = "plain") # for modelsummary output
```


# Estimation {.tabset}

## lau log-linear counterexample {.tabset}

### n = 50 {.tabset}

```{r,echo=TRUE,results = "asis"}
generate_plot_log_log(
    counterexample_for_Lau1982_n_50_sigma_0.001
  )
generate_plot_log_log(
    counterexample_for_Lau1982_n_50_sigma_0.5
  )
generate_plot_log_log(
    counterexample_for_Lau1982_n_50_sigma_1
  )
generate_plot_log_log(
    counterexample_for_Lau1982_n_50_sigma_2
  )
```


### n = 100

```{r,echo=TRUE,results = "asis"}
generate_plot_log_log(
    counterexample_for_Lau1982_n_100_sigma_0.001
  )
generate_plot_log_log(
    counterexample_for_Lau1982_n_100_sigma_0.5
  )
generate_plot_log_log(
    counterexample_for_Lau1982_n_100_sigma_1
  )
generate_plot_log_log(
    counterexample_for_Lau1982_n_100_sigma_2
  )
```


### n = 200 {.tabset}

```{r,echo=TRUE,results = "asis"}
generate_plot_log_log(
    counterexample_for_Lau1982_n_200_sigma_0.001
  )
generate_plot_log_log(
    counterexample_for_Lau1982_n_200_sigma_0.5
  )
generate_plot_log_log(
    counterexample_for_Lau1982_n_200_sigma_1
  )
generate_plot_log_log(
    counterexample_for_Lau1982_n_200_sigma_2
  )
```


### n = 1000 {.tabset}

```{r,echo=TRUE,results = "asis"}
generate_plot_log_log(
    counterexample_for_Lau1982_n_1000_sigma_0.001
  )
generate_plot_log_log(
    counterexample_for_Lau1982_n_1000_sigma_0.5
  )
generate_plot_log_log(
    counterexample_for_Lau1982_n_1000_sigma_1
  )
generate_plot_log_log(
    counterexample_for_Lau1982_n_1000_sigma_2
  )
```

